# Deploy static site to GitHub Pages and inject config.js from secrets
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create the runtime config.js with your Supabase values from repo secrets
      - name: Create runtime config
        run: |
          cat > config.js <<'EOF'
          window.PINGED_CONFIG = {
            SUPABASE_URL: "${{ secrets.SUPABASE_URL }}",
            SUPABASE_KEY: "${{ secrets.SUPABASE_ANON_KEY }}"
          };
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
